version: '3.8'

services:
  voltaris-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voltaris-website
    restart: unless-stopped
    expose:
      - 80
    environment:
      - API_URL=${API_URL:-/api}
      - APP_ENV=${APP_ENV:-production}
      - PUBLIC_URL=${PUBLIC_URL:-}
      - REACT_APP_CUSTOM_VARIABLE=${REACT_APP_CUSTOM_VARIABLE:-default_value}
    networks:
      - voltaris-network
    # Uncomment for mounted volumes during development
    # volumes:
    #  - ./build:/usr/share/nginx/html:ro

  # Reverse proxy for handling requests
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - voltaris-network

  # Certbot for SSL certificate generation and renewal
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx-proxy

networks:
  voltaris-network:
    driver: bridge