version: '3.8'

services:
  voltaris-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voltaris-website
    restart: unless-stopped
    expose:
      - 80
    environment:
      - API_URL=${API_URL:-/api}
      - APP_ENV=${APP_ENV:-production}
      - PUBLIC_URL=${PUBLIC_URL:-}
      - REACT_APP_CUSTOM_VARIABLE=${REACT_APP_CUSTOM_VARIABLE:-default_value}
    networks:
      - voltaris-network
    # Uncomment for mounted volumes during development
    # volumes:
    #  - ./build:/usr/share/nginx/html:ro

  # Reverse proxy for handling requests
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - voltaris-network

networks:
  voltaris-network:
    driver: bridge